spring:
  mvc:
    dispatch-options-request: true
  banner-mode: false

  datasource:
    url: 'jdbc:postgresql:spring_forum_db'
    username: postgres
    password: password12
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    database: 'POSTGRESQL'
    show-sql: false
    hibernate:
      ddl-auto: 'create-drop'
      dialect: 'org.hibernate.dialect.PostgreSQL9Dialect'
  show-sql: true

  mail:
    activation-link: localhost:8080/public/users/activate-account?token= #must be parametrized with token

    host: smtp.mailtrap.io
    port: 25
    username: 91f05e81b0403f
    password: 9e49565445af78
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  issuer: mpacala00
  expiration-sec: 86400 #one day in seconds
  clock-skew-sec: 300
  #some random jwt secret from a password generating site
  secret: '26SCT49ibP2QcBO94jLjbjTsoWa5laExtjm0ddleKcMg9JWBMyV9CjH7JCQ24H7'